version: "3.7"
services:
  mongodb-service:
    container_name: mongodb
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=PERSONDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db

  springreactivewebapp-service:
    container_name: springreactivewebapp
    image: amsidhmicroservice/springreactivewebapp:latest
    ports:
      - "8282:8282"
    restart: always
    depends_on: # This start the dependent service first
      - mongodb-service

  springreactiveangular-service:
    container_name: springreactiveangular
    image: amsidhmicroservice/springreactiveangular:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    restart: always
    depends_on: # This start the dependent service first
      - springreactivewebapp-service

